name: gammal_tech
description: A companion package to the Gammal Tech courses.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.10
  provider: ^6.0.3
  http: ^0.13.4
  youtube_player_flutter: ^8.1.0
  galleryimage: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
